name = "XLFunctions"
uuid = "9431f398-842c-4cdd-8867-ad7f58b28a5c"
authors = ["AutoActuary"]
version = "0.1.0"

[deps]
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
